/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AppointmentChecker": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "FailedApiRequestsQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "HEALTHIE_API": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HEALTHIE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "RemindersTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
